### ratings.data - 영화평점 데이터
- loadtxt()
- delimiter
- dtype

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
# userId, movieId, rating, timestamp
data = np.loadtxt('./data/ratings.dat', delimiter = "::", dtype = np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [7]:
def arrInfo(arr) :
    print('type : {}'.format(type(arr)))
    print('shape : {}'.format(arr.shape))
    print('dimension : {}'.format(arr.ndim))
    print('dtype : {}'.format(arr.dtype))
    print('Array Data : \n', arr)

In [8]:
arrInfo(data)

type : <class 'numpy.ndarray'>
shape : (1000209, 4)
dimension : 2
dtype : int64
Array Data : 
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [24]:
# 데이터의 첫 5 행만 확인
print(data[:5])

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]


In [25]:
# 데이터의 형태 확인
print(type(data))

<class 'numpy.ndarray'>


In [26]:
# 전체 평균 평점 계산
print(round(np.mean(data[:, 2]), 2))

3.58


In [27]:
# 사용자 아이디 수집
user_ids = np.unique(data[:, 0])
print(user_ids)

[   1    2    3 ... 6038 6039 6040]


In [28]:
# 사용자별 평점의 평균 확인
mean_userids = []

for user in user_ids :
    data_for_user = data[user == data[:, 0], :]
    # print(data_for_user)
    user_mean = data_for_user[:, 2].mean()
    # print(user_mean)
    mean_userids.append([user, user_mean])

mean_userids[:5]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466]]

In [31]:
# 리스트를 Numpy 배열로 변환
mean_userids_arary = np.array(mean_userids, dtype = np.float32)
print(mean_userids_arary[:5])
print(mean_userids_arary.shape)
print(type(mean_userids_arary))

[[1.        4.188679 ]
 [2.        3.7131784]
 [3.        3.9019608]
 [4.        4.1904764]
 [5.        3.1464646]]
(6040, 2)
<class 'numpy.ndarray'>


In [35]:
# csv 파일 저장
np.savetxt('./data/movies_mean_userids.csv', mean_userids_arary, delimiter = ',', fmt = '%.1f')